[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Disable Netlify Service Worker completely
[[redirects]]
  from = "/cnm-sw.js"
  to = "/404.html"
  status = 404

# Headers for CSV files
[[headers]]
  for = "*.csv"
  [headers.values]
    Content-Type = "text/csv; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/Libro2.csv"
  [headers.values]
    Content-Type = "text/csv; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Robots-Tag = "noindex"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200