[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Headers for CSV files
[[headers]]
  for = "*.csv"
  [headers.values]
    Content-Type = "text/csv; charset=utf-8"
    Cache-Control = "public, max-age=3600"

# Disable Service Worker for CSV files
[[headers]]
  for = "/Libro2.csv"
  [headers.values]
    Content-Type = "text/csv; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200